### ISSUE TITLE
Facing errors in starting the server

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#188]
Followed the instructions in the readme.md to run the blog site on the server, faced this error repeatedly with every blog post that we have. I think the instructions are bit outdated.

```
ERROR: Could not process blog/announce-oyo-rooms-as-accomodation-partner-2018.md
  | Failed loading extension "codehilite(css_class=highlight)".
  |___
  | Traceback (most recent call last):
  |   File "/home/vipulgupta2048/.virtualenvs/pycon-blog/local/lib/python2.7/site-packages/pelican/generators.py", line 502, in generate_context
  |     context_sender=self)
  |   File "/home/vipulgupta2048/.virtualenvs/pycon-blog/local/lib/python2.7/site-packages/pelican/readers.py", line 459, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/vipulgupta2048/.virtualenvs/pycon-blog/local/lib/python2.7/site-packages/pelican/readers.py", line 236, in read
  |     self._md = Markdown(extensions=self.extensions)
  |   File "/home/vipulgupta2048/.virtualenvs/pycon-blog/local/lib/python2.7/site-packages/markdown/core.py", line 100, in __init__
  |     configs=kwargs.get('extension_configs', {}))
  |   File "/home/vipulgupta2048/.virtualenvs/pycon-blog/local/lib/python2.7/site-packages/markdown/core.py", line 126, in registerExtensions
  |     ext = self.build_extension(ext, configs.get(ext, {}))
  |   File "/home/vipulgupta2048/.virtualenvs/pycon-blog/local/lib/python2.7/site-packages/markdown/core.py", line 166, in build_extension
  |     module = importlib.import_module(ext_name)
  |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
  |     __import__(name)
  | ImportError: Failed loading extension "codehilite(css_class=highlight)".
```

**Comment by vipulgupta2048** [comment]
Checked this extension, its mentioned alright in requirements.txt but still failed to load.

**Comment by ananyo2012** [comment]
Seems like pelican uses this. Can you check which version of pelican is installed in the virtualenv ?

**Comment by vipulgupta2048** [comment]
Yup, that was it. Updated the same in requirements file for future references. 
Pelican version now is `3.7.1`
Refer #190 for the same. Thanks.

**Comment by ananyo2012** [comment]
Yup sometimes some dependencies change and the fix is rolled out only in
newer versions. I will have a look at the PR later tonight
